site_name: ITF Documentation
site_url: https://amidentity.com/
nav:
    - Home: index.md
    - Introduction:
        - ITF Testing Concepts: 'ITF Testing concepts.md'
    - Installation:
        - Installation and configuration: 'ITF Installation and configuration.md'
        - IIQ ITF Plugin installation: 'Deploy ITF IdentityIQ plugin.md'
    - Reference:
        - Command reference: 'ITF XML Reference.md'
    - About: 'about.md'
theme: readthedocs
