site_name: ITF Documentation
site_url: https://amidentity.com/
nav:
    - Home: index.md
    - Introduction:
        - ITF Testing Concepts: 'ITF Testing concepts.md'
    - Installation:
        - Installation and configuration: 'ITF Installation and configuration.md'
        - IIQ ITF Plugin installation: 'Deploy ITF IdentityIQ plugin.md'
        - Install IntelliJ ITF plugin: 'Install IntelliJ ITF plugin.md'
        - Configuring ITF in the SSB build: 'Configuring ITF in the SSB build.md'
        - Configuring ITF libraries for IntelliJ: 'Configuring ITF libraries for IntelliJ.md'
        - Configuring ITF DTD for IntelliJ: 'Configuring ITF DTD for IntelliJ.md'
        - Configuring ITF libraries for Eclipse: 'Configuring ITF libraries for Eclipse.md'
        - Configuring ITF DTD for Eclipse: 'Configuring ITF DTD for Eclipse.md'
    - Reference:
        - Command reference: 'ITF XML Reference.md'
        - Pseudo date handling: 'Pseudo date handling.md'
        - Test identity generator: 'Test identity generator.md'
    - IntelliJ plugin:
        - Plugin capabilities: 'IntelliJFunc.md'
    - Release notes: 'Release notes.md'
theme: readthedocs
extra_css:
  - css/itf_doc.css
